name: Quality

on:
  push:
    branches: [main, "feat/**", "fix/**"]
  pull_request:

jobs:
  quality:
    uses: flipslidersand-labs/qa-workflows/.github/workflows/node-test.yml@main
    with:
      node-version: "20"
      package-manager: "npm"
      run-lint: false
      run-test: false
      runner: ubuntu-latest
